spring.application.name=easylab_backend

# ==========================================
# MySQL Configuration
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/easylab_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Lima
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# JWT Configuration
# ==========================================
jwt.secret=easylab-secret-key-super-segura-2024-debe-tener-al-menos-256-bits-ok
jwt.expiration=86400000

# ==========================================
# Server
# ==========================================
server.port=8080

# ==========================================
# Springdoc OpenAPI / Swagger UI
# ==========================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
